### 학습 목표

- 배열과 리스트의 차이점 
- 배열 생성 다루는 기법
- 기술 통계
- 결과에 대한 분석하는 방법

- 넘파이의 배열은 모든 원소가 같은 자료형이여야 한다.
- resizing 이 안된다.

- Vector(1차원 - 배열) - pandas(Series)
- Martrix(2차원 - 행렬) - pandas(DataFrame)

- 선형대수(행렬을 이용한 연산가능)

In [2]:
import numpy as np

- 배열의 차원과 크기 타입
- ndim,shape,dtype

In [10]:
def aryinfo(ary):
    print('type : {}'.format(type(ary)))
    print('shape : {}'.format(ary.shape))
    print('dimension : {}'.format(ary.ndim))
    print('dtype : {}'.format(ary.dtype))
    print('Array Data : \n',ary)

# 1 차원 배열 생성
- array()

In [11]:
oneAry = np.array([0,1,2,3,4,5,6,7,8,9])
aryinfo(oneAry)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : int32
Array Data : 
 [0 1 2 3 4 5 6 7 8 9]


In [8]:
oneAry

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- List vs Array 차이점

In [12]:
data = [0,1,2,3,4,5,6,7,8,9]
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
result = []
for d in data:
    result.append(d*2)
result

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [14]:
result2 = [d*2 for d in data]
result2

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [15]:
result3 = oneAry * 2
result3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

- 벡터 연산은 비교,산술,논리 연산을 포함하는 모든 수학 연산에 적용됨

In [16]:
xAry = np.array([1,2,3])
yAry = np.array([10,20,30])

In [19]:
2*xAry + yAry

array([12, 24, 36])

In [20]:
xAry == 2

array([False,  True, False])

In [21]:
yAry > 20

array([False, False,  True])

In [22]:
(xAry ==2) & (yAry >20)

array([False, False, False])

# 2차원 배열 생성
- ndarray(N-dimensional Array
- 2차원, 3차원(다차원 배열 자료구조)
- list of list
- list of list of list

In [29]:
# 2개의 행과 3개의 열을 가지는 배열을 만든다면
twoAry = np.array([[1,2,3],[4,5,6]], dtype=np.float64)

In [30]:
aryinfo(twoAry)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension : 2
dtype : float64
Array Data : 
 [[1. 2. 3.]
 [4. 5. 6.]]


In [28]:
# 행의 개수, 열의 개수
print(len(twoAry)) # 행의 개수
print(len(twoAry[0])) # 열의 개수
print(len(twoAry[1])) # 열의 개수

2
3
3


# 3 차원 배열 생성

In [42]:
# 2 3 4
threeAry = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
                     [[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
aryinfo(threeAry)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4)
dimension : 3
dtype : int32
Array Data : 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [41]:
print('dept',len(threeAry)) # 길이
print('row',len(threeAry[0])) # 행
print('row[0]_col',len(threeAry[0][0])) # 열

dept 2
row 3
row[0]_col 4


- 요소의 타입을 변경할 때는 astype()

In [44]:
typeChange = threeAry.astype(np.float64)
aryinfo(typeChange)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4)
dimension : 3
dtype : float64
Array Data : 
 [[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[13. 14. 15. 16.]
  [17. 18. 19. 20.]
  [21. 22. 23. 24.]]]


In [45]:
indexAry = np.array([1,2,3,4,5,6,7])
aryinfo(indexAry)

type : <class 'numpy.ndarray'>
shape : (7,)
dimension : 1
dtype : int32
Array Data : 
 [1 2 3 4 5 6 7]


In [47]:
indexAry[2]

3

In [48]:
indexAry[-1]

7

In [55]:
# twoAry indexing
# 첫번째 행의 첫번째 열
print(twoAry[0][0])
print(twoAry[0,0])
# 첫번째 행의 두번째 열
print(twoAry[0][1])
print(twoAry[0,1])
# 마지막 행의 마지막 열
print(twoAry[-1][-1])
print(twoAry[-1,-1])


1.0
1.0
2.0
2.0
6.0
6.0


In [60]:
slicingAry = np.array([[1,2,3,4],
                       [5,6,7,8]])

# 첫번째 행의 전체
print(slicingAry[0])
# 두번째 열의 전체
print(slicingAry[:,1])
# 두번째 행의 두번째 열부터 끝까지
print(slicingAry[1,1:])

[1 2 3 4]
[2 6]
[6 7 8]


In [62]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
# 이 행렬에서 값 7을 인덱싱한다.
# 이 행렬에서 값 14를 인덱싱한다.
# 이 행렬에서 배열 [6,7]을 슬라이싱 한다.
# 이 행렬에서 배열 [7,12] 을 슬라이싱 한다.
# 이 행렬에서 배열 [[3,4],[8,9]]을 슬라이싱한다.

In [70]:
print(m[1,2])
print(m[2,-1])
print(m[1,1:3])
print(m[1:,2])
print(m[0:2,3:5])


7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


- fancy Indexing
- boolean Indexing

In [73]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
aryinfo(arr)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : int32
Array Data : 
 [0 1 2 3 4 5 6 7 8 9]


In [81]:
arr % 2 ==0 # boolean Indexing

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [83]:
arr[arr % 2 ==0]

array([0, 2, 4, 6, 8])

In [84]:
cntIdx = np.array([0,2,4,6,8])
print(arr[cntIdx])

[0 2 4 6 8]


In [86]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 이 배열에서 3의 배수를 찾아라
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라
# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라

In [102]:
print(x[x%3==0])
print(x[x%4==1])
print(x[(x%3==0)&(x%4==1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


In [104]:
# 배열에 index 배열을 전달하여 배열 요소를 참조해 보자
fancyAry = np.arange(0,12,1).reshape(3,4)
aryinfo(fancyAry)

type : <class 'numpy.ndarray'>
shape : (3, 4)
dimension : 2
dtype : int32
Array Data : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [110]:
# 10 값을 가져온다면?
fancyAry[2,2]

10

In [112]:
# 6의 값을 가져온다면?
fancyAry[1:2,2]

array([6])

In [114]:
fancyAry[1:2,:]

array([[4, 5, 6, 7]])

In [116]:
aryinfo(fancyAry[1:2,1:2])

type : <class 'numpy.ndarray'>
shape : (1, 1)
dimension : 2
dtype : int32
Array Data : 
 [[5]]


In [135]:
# 2와 10 값을 가져온다면?
fancyAry[[0,2],2] # 사용하는 행은 0 행과 2번째 행이고 가지고 오는 값은 2번째 값이란 뜻이다.

array([ 2, 10])

In [134]:
# 2와 10 값을 가져온다면?
fancyAry[[0,2],2:3] # 사용하는 행은 0 행과 2번째 행이고 가지고 오는 값은 2번째 값이란 뜻이다.

array([[ 2],
       [10]])

In [157]:
rowidx = np.array([0,2])
colidx = np.array([0,2])

print(fancyAry[ [rowidx]] [:,colidx])

[[ 0  2]
 [ 8 10]]


C:\Users\hwang in beom\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  after removing the cwd from sys.path.


# 배열 변형(타입 형태)

In [162]:
x = np.array([1,2,3],dtype='U')
aryinfo(x)

type : <class 'numpy.ndarray'>
shape : (3,)
dimension : 1
dtype : <U1
Array Data : 
 ['1' '2' '3']


In [163]:
x[0] + x[1]

'12'

- inf vs Nan

In [164]:
np.array([0, 1, -1, 0]/np.array([1, 0, 0, 0]))

C:\Users\hwang in beom\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\hwang in beom\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0.,  inf, -inf,  nan])

- zeors, ones # 0으로 배열을 셋팅 / 1로 배열을 셋팅
- zeros_like, ones_like # shape를 참조 해서 0 으로 만든다. / shape를 참조 해서 1 으로 만든다.
- empty
- arrang
- linspace, logspace

- zeors: 크기가 정해져 있고 모든 값이 0인 배열을 생성

In [167]:
z = np.zeros(5)
aryinfo(z)

type : <class 'numpy.ndarray'>
shape : (5,)
dimension : 1
dtype : float64
Array Data : 
 [0. 0. 0. 0. 0.]


In [168]:
o = np.ones((2,3,4),dtype='i8')
aryinfo(o)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4)
dimension : 3
dtype : int64
Array Data : 
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [173]:
o_like = np.ones_like(o, dtype='f') # 기존 배열의 형태를 참조한다.
aryinfo(o_like)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4)
dimension : 3
dtype : float32
Array Data : 
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [174]:
z_like = np.zeors_like(z)
anyinfo(z_like)

AttributeError: module 'numpy' has no attribute 'zeor_like'

In [175]:
e = np.empty((4,3))
aryinfo(e)

type : <class 'numpy.ndarray'>
shape : (4, 3)
dimension : 2
dtype : float64
Array Data : 
 [[0.0078125 0.0078125 0.0078125]
 [0.0078125 0.0078125 0.0078125]
 [0.0078125 0.0078125 0.0078125]
 [0.0078125 0.0078125 0.0078125]]


In [176]:
a = np.arange(10)
aryinfo(a)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : int32
Array Data : 
 [0 1 2 3 4 5 6 7 8 9]


In [178]:
a = np.arange(3,21,2)
aryinfo(a)

type : <class 'numpy.ndarray'>
shape : (9,)
dimension : 1
dtype : int32
Array Data : 
 [ 3  5  7  9 11 13 15 17 19]


- 전치행렬(transpose matirx)이란? 행렬의 행은 열로, 열은 행으로 바꾼 행렬을 의미한다.
- 속성 T
- transpose opertion

In [180]:
# vector 에 transpose 가능할까?
vec = np.arange(10)
aryinfo(vec)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : int32
Array Data : 
 [0 1 2 3 4 5 6 7 8 9]


In [181]:
vec_transpose = vec.T
aryinfo(vec_transpose)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : int32
Array Data : 
 [0 1 2 3 4 5 6 7 8 9]


In [184]:
vec_transpose = vec.reshape(1,10)
aryinfo(vec_transpose)

type : <class 'numpy.ndarray'>
shape : (1, 10)
dimension : 2
dtype : int32
Array Data : 
 [[0 1 2 3 4 5 6 7 8 9]]


In [186]:
vec_transpose = vec.reshape(1,10).T
aryinfo(vec_transpose)

type : <class 'numpy.ndarray'>
shape : (10, 1)
dimension : 2
dtype : int32
Array Data : 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


- 배열의 원소를 순차적으로 access 하고자 한다면?
- for (Vector, Matrix)
- iterator(internext(), finished 속성을 이용해서 ndarray 모든 요소를 순차적으로 접근 할 수 있다.)

In [187]:
arr = np.array([1,2,3,4,5])

In [188]:
for tmp in arr:
    print(tmp, end=" ")

1 2 3 4 5 

In [190]:
for idx in range(len(arr)):
    print(arr[idx],end=" ")

1 2 3 4 5 

In [194]:
ite = np.nditer(arr, flags=['c_index'])
while not ite.finished:# 순환 반복 속성이다.
    print(arr[ite.index], end = " ")
    ite.iternext()

1 2 3 4 5 

In [204]:
arr = np.array([[1,2,3],[4,5,6]])
aryinfo(arr)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension : 2
dtype : int32
Array Data : 
 [[1 2 3]
 [4 5 6]]


In [205]:
for x in range(len(arr)):
    for y in range(len(arr[0])):
        print(arr[x,y], end = " ")


1 2 3 4 5 6 

In [207]:
# 2차원 배열에 대한 순차적 접근 코드 작성
# print(arr.shape[0] : row)
# print(arr.shpae[1]) : col

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        print(arr[i,j], end="\t")
    print("\n")

1	2	3	

4	5	6	



In [209]:
ite = np.nditer(arr, flags=['multi_index'])
while not ite.finished:# 순환 반복 속성이다.
    print(arr[ite.multi_index], end = " ")
    ite.iternext()

1 2 3 4 5 6 